source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload
plug "evanrelf/number-toggle.kak" config %{
      require-module "number-toggle"
}
plug 'delapouite/kakoune-auto-percent'
plug 'Delapouite/kakoune-auto-star'
plug 'alexherbo2/auto-pairs.kak'
set-option global auto_pairs ( ) { } [ ] '"' '"' "'" "'" ` ` “ ” ‘ ’ « » ‹ ›
enable-auto-pairs

plug 'h-youhei/kakoune-surround'

plug 'andreyorst/fzf.kak' %{
    map global user "f" ': fzf-mode<ret>' -docstring 'Fuzzy Find'
}

plug 'occivink/kakoune-phantom-selection'
plug 'occivink/kakoune-sort-selections'

plug 'Delapouite/kakoune-buffers'
plug 'greenfork/active-window.kak'

plug 'danr/kakoune-easymotion'

plug 'lePerdu/kakboard' %{
    hook global WinCreate .* %{ kakboard-enable }
}

plug 'occivink/kakoune-vertical-selection' %{
}

plug 'delapouite/kakoune-text-objects' %{
    map global normal ': enter-user-mode selectors<ret>' -docstring 'selectors'
    map global selectors ': if-cursor s s<ret>' -docstring 'auto-percent s' -docstring 'Sub-Selection'
}

plug 'delapouite/kakoune-select-view' %{
  # Suggested mappings
  map global normal <a-%> ': select-view<ret>' -docstring 'select view'
  map global view s '<esc>: select-view<ret>' -docstring 'select view'
}

plug 'delapouite/kakoune-mirror' %{
  # Suggested mapping
  map global user "m" ': enter-user-mode -lock mirror<ret>' -docstring 'Mirror'
}

plug 'delapouite/kakoune-hump'
plug 'https://gitlab.com/FlyingWombat/case.kak' %{
    map global user 's' ': enter-user-mode case<ret>' -docstring 'change case'
}

plug 'danr/kakoune-easymotion' %{
    map global user 'w' ':easy-motion-f<ret>' -docstring 'easy motion'
}

plug 'https://gitlab.com/Screwtapello/kakoune-inc-dec'

map global normal <c-]> <a-)>
map global normal <c-[> <a-(>

map global normal : \;
map global normal \; :

hook global NormalIdle .* %{ wa }

colorscheme tomorrow-night
def ide %{
    rename-client main
    set global jumpclient main

    new rename-client tools
    set global toolsclient tools

    new rename-client docs
    set global docsclient docs
}

def -params 1 extend-line-down %{
  exec "<a-:>%arg{1}X"
}
def -params 1 extend-line-up %{
  exec "<a-:><a-;>%arg{1}K<a-;>"
  try %{
    exec -draft ';<a-K>\n<ret>'
    exec X
  }
  exec '<a-;><a-X>'
}
map global normal x ':extend-line-down %val{count}<ret>'
map global normal X ':extend-line-up %val{count}<ret>'
