local m = require("mapx").setup({ global = true, whichkey = true })

-- Leader Mapping
vim.opt.timeoutlen = 500
vim.api.nvim_set_var("mapleader", " ")
vim.api.nvim_set_var("maplocalleader", "\\")

noremap("<BackSPACE>", "<Nop>")
noremap("<SPACE>", "<Nop>")

-- Whichkey setup
require("which-key").setup({
    plugins = {
        presets = {
            operators = true,
            motions = true,
            text_objects = true,
            windows = false,
            nav = false,
            z = false,
            g = false,
        },
    },
    operators = {
        [",c"] = "Comments",
        [",t"] = "Allign",
        [",r"] = "Replace",
        [",sp"] = "Change to Pascal Case",
        [",sc"] = "Change to Camel Case",
        [",ss"] = "Change to Snake Case",
        [",su"] = "Change to Upper Case",
        [",st"] = "Change to Title Case",
        [",sd"] = "Change to Sentance Case",
        [",s<space>"] = "Change to Space Case",
        [",s-"] = "Change to Kebab Case",
        [",sk"] = "Change to Title Kebab Case",
        [",s."] = "Change to Dot Case",
        ["gp"] = "Paste After",
        ["gP"] = "Paste Before",
        ["{"] = "Goto Left Outside",
        ["("] = "Goto Left Inside",
        [")"] = "Goto Right Inside",
        ["}"] = "Goto Right Outside",
        ["g{"] = "Insert Left Outside",
        ["g("] = "Insert Left Inside",
        ["g)"] = "Insert Right Inside",
        ["g}"] = "Insert Right Outside",
    },
    hidden = { "<silent>", "<cmd>", "<Cmd>", "<CR>", "call", "lua", "^:", "^ ", "<plug>", "<Plug>" },
    show_help = false,
})

-- Un-Mappings
noremap("v", "<nop>")
noremap("V", "<nop>")
noremap("<c-v>", "<nop>")
noremap("dd", "<nop>")
noremap("cc", "<nop>")
noremap("yy", "<nop>")
noremap("z", "<nop>")

noremap("Y", "<nop>")
noremap("C", "<nop>")
noremap("D", "<nop>")
noremap("S", "<nop>")

-- NOTE: _, =, |, ^, ¬ and # are free to map

-- Mappings
nnoremap(";", ":")
nnoremap(":", ";")
xnoremap(";", ":")
xnoremap(":", ";")
onoremap(";", ":")
onoremap(":", ";")

nnoremap("<m-f>", ";")
nnoremap("<m-F>", ",")
nnoremap("<m-t>", ";")
nnoremap("<m-T>", ",")
xnoremap("<m-f>", ";")
xnoremap("<m-F>", ",")
xnoremap("<m-t>", ";")
xnoremap("<m-T>", ",")

nnoremap("g<c-a>", "v<c-a>")
nnoremap("g<c-x>", "v<c-x>")
nnoremap("+", "<c-a>")
nnoremap("-", "<c-x>")
nnoremap("g+", "v<c-a>")
nnoremap("g-", "v<c-x>")
xnoremap("+", "<c-a>")
xnoremap("-", "<c-x>")
xnoremap("g+", "g<c-a>")
xnoremap("g-", "g<c-x>")

xnoremap("y", "m1y`1", "nowait")
xnoremap("d", "d", "nowait")
xnoremap("c", "c", "nowait")

nnoremap("x", "V")
nnoremap("X", "V")
nnoremap("C", "<c-v>j")
nnoremap("<m-C>", "<c-v>k")
nnoremap("<M-v>", "v")

xnoremap("x", "j$")
xnoremap("X", "<esc>`<kV`>")
xnoremap("C", "j")
xnoremap("<m-C>", "<esc>`<k<c-v>`>")
xnoremap("<M-v>", "v")
xnoremap("<M-;>", "o")

nnoremap("<m-c>", [["_c]])
nnoremap("<m-d>", [["_d]])
xnoremap("<m-c>", [["_c]])
xnoremap("<m-d>", [["_d]])

nnoremap("<m-o>", "m1o<esc>`1")
nnoremap("<m-O>", "m1O<esc>`1")

nnoremap("]", "<cmd>WhichKey ] n<cr>")
xnoremap("]", "<cmd>WhichKey ] x<cr>")
nnoremap("[", "<cmd>WhichKey [ n<cr>")
xnoremap("[", "<cmd>WhichKey [ x<cr>")
-- nnoremap(",", "<cmd>WhichKey g, n<cr>")
-- xnoremap(",", "<cmd>WhichKey g, x<cr>")
xnoremap("I", "I")
xnoremap("A", "A")

nnoremap("mm", "<cmd>lua require'harpoon.mark'.add_file()<cr>")
nnoremap("ma", "<cmd>lua require'harpoon.ui'.nav_file(1)<cr>")
nnoremap("mr", "<cmd>lua require'harpoon.ui'.nav_file(2)<cr>")
nnoremap("ms", "<cmd>lua require'harpoon.ui'.nav_file(3)<cr>")
nnoremap("mt", "<cmd>lua require'harpoon.ui'.nav_file(4)<cr>")
nnoremap("M", "<cmd>lua require'harpoon.ui'.toggle_quick_menu()<cr>")

nmap("<c-_>", "g,cc")
xmap("<c-_>", "g,c")

nnoremap("£", [[:exe "let @/='" . expand("<cWORD>") . ", "<cr>]])
nmap("<c-p>", "a<c-p>")

-- inoremap( "<c-y>", [[matchstr(getline(line('.')-1),'\%'.virtcol('.').'v\%(\k\+\\|.\)']], {"nowait", "expr"})
-- inoremap( "<c-l>", [[matchstr(getline(line('.')+1),'\%'.virtcol('.').'v\%(\k\+\\|.\)']], {"nowait", "expr"})
-- snoremap( "<c-y>", [[matchstr(getline(line('.')-1),'\%'.virtcol('.').'v\%(\k\+\\|.\)']], {"nowait", "expr"})
-- snoremap( "<c-l>", [[matchstr(getline(line('.')+1),'\%'.virtcol('.').'v\%(\k\+\\|.\)']], {"nowait", "expr"})

vim.cmd([[inoremap <expr> <nowait> <c-y> matchstr(getline(line('.')-1),'\%'.virtcol('.').'v\%(\k\+\\|.\)')]])
vim.cmd([[inoremap <expr> <nowait> <c-l> matchstr(getline(line('.')+1),'\%'.virtcol('.').'v\%(\k\+\\|.\)')]])
vim.cmd([[snoremap <expr> <nowait> <c-y> matchstr(getline(line('.')-1),'\%'.virtcol('.').'v\%(\k\+\\|.\)')]])
vim.cmd([[snoremap <expr> <nowait> <c-l> matchstr(getline(line('.')+1),'\%'.virtcol('.').'v\%(\k\+\\|.\)')]])

inoremap("<c-g>", "<c-o>%")
inoremap("<c-s>", "<cmd>lua require('lsp_signature').toggle_float_win()<CR>")

inoremap(",", ",<c-g>u")
inoremap(".", ".<c-g>u")
inoremap("!", "!<c-g>u")
inoremap("?", "?<c-g>u")

-- Panel Specific Mappings
vim.cmd([[augroup panelMappings
    autocmd!
    autocmd filetype qf                  map <buffer> <esc> <cmd>q<cr>
    autocmd filetype help                map <buffer> <esc> <cmd>q<cr>
    autocmd filetype vim-plug            map <buffer> <esc> <cmd>q<cr>
    autocmd filetype juliadoc            map <buffer> <esc> <cmd>q<cr>
    autocmd filetype undotree            map <buffer> <esc> <cmd>UndotreeHide<cr>
    autocmd filetype lspinfo             map <buffer> <esc> <cmd>q<cr>
    autocmd filetype DiffviewFiles       map <buffer> <esc> <cmd>DiffviewClose<cr>
    autocmd filetype DiffviewFileHistory map <buffer> <esc> <cmd>DiffviewClose<cr>
    autocmd filetype tsplayground        map <buffer> <esc> <cmd>q<cr>
    autocmd filetype harpoon-menu        map <buffer> <esc> <cmd>wq<cr>
augroup END]])

vim.api.nvim_set_var("wordmotion_prefix", "$")

-- UnMap Plugins
vim.api.nvim_set_var("kitty_navigator_no_mappings", true)
vim.api.nvim_set_var("UnconditionalPaste_no_mappings", true)
vim.api.nvim_set_var("caser_no_mappings	=", true)
vim.api.nvim_set_var("textobj_markdown_no_default_key_mappings", true)
vim.api.nvim_set_var("julia_blocks", false)

nnoremap("j", [[v:count?(v:count>5?"m'".v:count:'').'j':'gj']], "expr")
nnoremap("k", [[v:count?(v:count>5?"m'".v:count:'').'k':'gk']], "expr")
xnoremap("j", [[v:count?(v:count>5?"m'".v:count:'').'j':'gj']], "expr")
xnoremap("k", [[v:count?(v:count>5?"m'".v:count:'').'k':'gk']], "expr")
onoremap("j", [[v:count?(v:count>5?"m'".v:count:'').'j':'gj']], "expr")
onoremap("k", [[v:count?(v:count>5?"m'".v:count:'').'k':'gk']], "expr")

nnoremap("H", [[getline('.')[0:col('.')-2]=~#'^\s\+$'?'0':'^']], "expr")
nnoremap("L", [[getline('.')[col('.'):-1]=~#'^\s\+$'?'$':'g_']], "expr")
xnoremap("H", [[getline('.')[0:col('.')-2]=~#'^\s\+$'?'0':'^']], "expr")
xnoremap("L", [[getline('.')[col('.'):-1]=~#'^\s\+$'?'$':'g_']], "expr")
onoremap("H", [[getline('.')[0:col('.')-2]=~#'^\s\+$'?'0':'^']], "expr")
onoremap("L", [[getline('.')[col('.'):-1]=~#'^\s\+$'?'$':'g_']], "expr")

nnoremap("J", "gi")
nnoremap("U", "<c-r>")
xnoremap("U", "<c-r>")

xnoremap("J", ":move '>+1<cr>gv=gv")
xnoremap("K", ":move '<-2<cr>gv=gv")

nnoremap("Q", "@q")
xnoremap("Q", ":norm! @q<cr>")

nnoremap("s", "<cmd>lua require'hop'.hint_char1()<cr>")
nnoremap("S", "<cmd>ISwapWith<cr>")
xnoremap("s", "<cmd>lua require'hop'.hint_char1()<cr>")
xnoremap("S", ":lua require('tsht').nodes()<CR>")
onoremap("s", "<cmd>lua require'hop'.hint_char1()<cr>")
onoremap("S", ":<c-u>lua require('tsht').nodes()<cr>")


nnoremap("'", "`")
nnoremap("`", "'")
xnoremap("'", "`")
xnoremap("`", "'")
onoremap("'", "`")
onoremap("`", "'")

xnoremap("<", "<gv")
xnoremap(">", ">gv")

nnoremap("<right>", "<cmd>bnext<cr>")
nnoremap("<left>", "<cmd>bprevious<cr>")
nnoremap("<C-right>", "<cmd>tabnext<cr>")
nnoremap("<C-left>", "<cmd>tabprevious<cr>")
nnoremap("<S-right>", "<cmd>tabnext<cr>")
nnoremap("<S-left>", "<cmd>tabprevious<cr>")

nnoremap("<c-t>", "<cmd>tabedit #<cr>")
nnoremap("<c-v>", "<cmd>vsplit #<cr>")
nnoremap("<c-x>", "<cmd>split #<cr>")

nmap("n", "v:lua.commandRepeat(']', 'dirJumps')", "expr")
vmap("n", "v:lua.commandRepeat(']', 'dirJumps')", "expr")
nmap("N", "v:lua.commandRepeat('[', 'dirJumps')", "expr")
vmap("N", "v:lua.commandRepeat('[', 'dirJumps')", "expr")

nnoremap("<cr><cr>", "<cmd>call v:lua.sendLines(v:count)<cr>")
nmap("<cr>", "<plug>(sendOp)")
xmap("<cr>", "<plug>(sendReg)")

m.name("g", "Goto")
    nnoremap("gg", "gg", "Buffer Top")
    nnoremap("gj", "G", "Buffer Bottom")
    nnoremap("gk", "gg", "Buffer Top")
    nnoremap("gh", "^", "Line Begining")
    nnoremap("gl", "$", "Line End")
    xnoremap("gg", "gg", "Buffer Top")
    xnoremap("gj", "G", "Buffer Bottom")
    xnoremap("gk", "gg", "Buffer Top")
    xnoremap("gh", "^", "Line Begining")
    xnoremap("gl", "$", "Line End")
    onoremap("gg", "gg", "Buffer Top")
    onoremap("gj", "G", "Buffer Bottom")
    onoremap("gk", "gg", "Buffer Top")
    onoremap("gh", "^", "Line Begining")
    onoremap("gl", "$", "Line End")

    nnoremap("gt", "H", "Window Top")
    nnoremap("gc", "M", "Window Center")
    nnoremap("gb", "L", "Window Bottom")
    xnoremap("gt", "H", "Window Top")
    xnoremap("gc", "M", "Window Bottom")
    xnoremap("gb", "L", "Window Center")
    onoremap("gt", "H", "Window Top")
    onoremap("gc", "M", "Window Bottom")
    onoremap("gb", "L", "Window Center")

    nnoremap("gf", "gf", "Open File")
    nnoremap("gF", "<cmd>vsplit<cr>gf", "Open File in Split")

    nnoremap("gd", "<cmd>lua require('telescope.builtin').lsp_definitions()<cr>", "Definitions")
    nnoremap("gr", "<cmd>Telescope lsp_references<cr>", "References")
    nnoremap("gi", "<cmd>lua require('telescope.builtin').lsp_implementations()<CR>", "Implementations")
    nnoremap("go", "<cmd>lua require('telescope.builtin').lsp_type_definitions()<cr>", "Object Deffinition")
    nnoremap("gD", "<cmd>lua require('telescope.builtin').lsp_definitions({jump_type='vsplit'})<cr>", "Definitions (split)")
    nnoremap("gR", "<cmd>lua require('telescope.builtin').lep_references({jump_type='vsplit'})<cr>", "References (split)")
    nnoremap("gI", "<cmd>lua require('telescope.builtin').lsp_implementations({jump_type='vsplit'})<CR>", "Implementations (split)")
    nnoremap("gO", "<cmd>lua require('telescope.builtin').lsp_type_definitions({jump_type='vsplit'})<cr>", "Object Deffinition (split)")

    nmap("gp", "<plug>(paste-away-after)", "Paste After Object")
    nmap("gP", "<plug>(paste-away-before)", "Paste Before Object")
    nmap("g{", "<Plug>(ninja-insert)a", "Go Insert Left Outside")
    nmap("g(", "<Plug>(ninja-insert)i", "Go Insert Left Inside")
    nmap("g)", "<Plug>(ninja-append)i", "Go Insert Right Inside")
    nmap("g}", "<Plug>(ninja-append)a", "Go Insert Right Outside")

m.name("G", "Goto (Select)")
    nnoremap("Gg", "vgg", "Buffer Top")
    nnoremap("Gj", "vG", "Buffer Bottom")
    nnoremap("Gk", "vgg", "Buffer Top")
    nnoremap("Gh", "v^", "Line Begining")
    nnoremap("Gl", "v$", "Line End")

    nnoremap("Gt", "vH", "Window Top")
    nnoremap("Gc", "vM", "Window Bottom")
    nnoremap("Gb", "vL", "Window Center")

m.name("v", "View")
    nnoremap("vt", "zt", "Cursor On Top")
    nnoremap("vv", "zz", "Centre Cursor (Vertically)")
    nnoremap("vc", "zz", "Centre Cursor (Vertically)")
    nnoremap("vb", "zb", "Cursor On Bottom")
    xnoremap("vt", "zt", "Cursor On Top")
    xnoremap("vv", "zz", "Centre Cursor (Vertically)")
    xnoremap("vc", "zz", "Centre Cursor (Vertically)")
    xnoremap("vb", "zb", "Cursor On Bottom")

    nnoremap("vf", "zs", "Cursor At First")
    nnoremap("vm", "<cmd>set sidescrolloff=999<cr><cmd>set sidescrolloff=0<cr>", "Centre Cursor (Horizontally)")
    nnoremap("ve", "ze", "Cursor At End")
    xnoremap("vf", "zs", "Cursor At First")
    xnoremap("vm", "<cmd>set sidescrolloff=999<cr><cmd>set sidescrolloff=0<cr>", "Centre Cursor (Horizontally)")
    xnoremap("ve", "ze", "Cursor At End")

    nnoremap("vh", "zh", "Scroll Left")
    nnoremap("vl", "zl", "Scroll Right")
    nnoremap("vj", "<c-e>", "Scroll Down")
    nnoremap("vk", "<c-y>", "Scroll Up")
    xnoremap("vh", "zh", "Scroll Left")
    xnoremap("vl", "zl", "Scroll Right")
    xnoremap("vj", "<c-e>", "Scroll Down")
    xnoremap("vk", "<c-y>", "Scroll Up")

    nnoremap("vu", "<c-u>", "Half Page Up")
    nnoremap("vd", "<c-d>", "Half Page Down")
    xnoremap("vu", "<c-u>", "Half Page Up")
    xnoremap("vd", "<c-d>", "Half Page Down")

    nnoremap("vs", "<cmd>normal! HVL<cr>", "Select Viewport")
    xnoremap("vs", "<cmd>normal! HVL<cr>", "Select Viewport")

m.name("V", "View (Lock)")
    nmap("Vt", "vt<cmd>WhichKey V<cr>", "Cursor On Top")
    nmap("Vv", "vv<cmd>WhichKey V<cr>", "Centre Cursor (Vertically)")
    nmap("Vb", "vb<cmd>WhichKey V<cr>", "Cursor On Bottom")

    nmap("Vf", "vf<cmd>WhichKey V<cr>", "Cursor At First")
    nmap("Vm", "vm<cmd>WhichKey V<cr>", "Centre Cursor (Horizontally)")
    nmap("Ve", "ve<cmd>WhichKey V<cr>", "Cursor At End")

    nmap("Vh", "vh<cmd>WhichKey V<cr>", "Scroll Left")
    nmap("Vl", "vl<cmd>WhichKey V<cr>", "Scroll Right")
    nmap("Vj", "vj<cmd>WhichKey V<cr>", "Scroll Down")
    nmap("Vk", "vk<cmd>WhichKey V<cr>", "Scroll Up")

    nmap("Vu", "vu<cmd>WhichKey V<cr>", "Half Page Up")
    nmap("Vd", "vd<cmd>WhichKey V<cr>", "Half Page Down")

m.name("z", "Select Mode")
    nmap("zh", "<m-v>{", "Left Outside")
    nmap("zn", "<m-v>(", "Left Inside")
    nmap("ze", "<m-v>)", "Right Inside")
    nmap("zl", "<m-v>}", "Right Outside")
    xmap("zh", "<esc><m-v>{", "Left Outside")
    xmap("zn", "<esc><m-v>(", "Left Inside")
    xmap("ze", "<esc><m-v>)", "Right Inside")
    xmap("zl", "<esc><m-v>}", "Right Outside")

    nmap("z{", "<m-v>{", "Left Outside")
    nmap("z(", "<m-v>(", "Left Inside")
    nmap("z)", "<m-v>)", "Right Inside")
    nmap("z}", "<m-v>}", "Right Outside")

    nmap("zi", "<m-v>i", "Inside")
    nmap("zo", "<m-v>a", "Outside")
    xmap("zi", "<esc><m-v>i", "Inside")
    xmap("zo", "<esc><m-v>a", "Outside")

m.name(",", "User Commands")
nnoremap(",;", "q:", "Command Buffer")
xnoremap(",;", "q:", "Command Buffer")
nnoremap(",.", "<cmd>Telescope lsp_code_actions theme=get_cursor<CR>", "Code Actions")
xnoremap(",.", "<cmd>Telescope lsp_range_code_actions theme=get_cursor<CR>", "Code Actions (Range)")

nnoremap(",j", "m1J`1", "Join")
nnoremap(",k", "i<cr><esc>", "Split")
xnoremap(",j", "J")
xnoremap(",k", "c<cr><esc>")

m.name(",c", "Comment")
nmap(",r", "<plug>(SubversiveSubstitute)", "Substitute")
xmap(",r", "<plug>(SubversiveSubstitute)", "Substitute")
nmap(",t", "<Plug>(EasyAlign)", "Easy Allign")
xmap(",t", "<Plug>(EasyAlign)", "Align")

nnoremap(",O", "O<Esc>", "Insert Blankline Before")
nnoremap(",o", "o<Esc>", "Insert Blankline")
    m.name(",f", "Format")
    nnoremap(",ff", "<cmd>lua vim.lsp.buf.formatting_sync()<CR>", "Format")
    nnoremap(",f<space>", [[<cmd>%s/\v[^^ ]\zs  / /g<cr>]], "Remove Double Spaces")
    nnoremap(",fw", [["m1!ippar w". &textwidth . "<cr>`1"]], "Wrap Paragraph to Textwidth", "expr")
    nnoremap(",fW", [["<cmd>%!par w" . &textwidth . "<cr>"]], "Wrap File to Textwidth", "expr")
    xnoremap(",ff", "<cmd>lua vim.lsp.buf.range_formatting()<CR>", "Format")
    xnoremap(",f<space>", ":%s/\v[^^ ]\zs  / /g<cr>", "Remove Double Spaces")
    xnoremap(",fw", [["!par w" . &textwidth . "<cr>"]], "Wrap to Textwidth", "expr")

    nnoremap(",fl", "<cmd>left<cr>", "Left Allign")
    nnoremap(",fc", "<cmd>center<cr>", "Centre Allign")
    nnoremap(",fr", "<cmd>right<cr>", "Right Allign")
    xnoremap(",fl", ":left<cr>", "Left Allign")
    xnoremap(",fc", ":center<cr>", "Centre Allign")
    xnoremap(",fr", ":right<cr>", "Right Allign")

    m.name(",P", "Paste Before")
    nmap(",Pb", "<Plug>UnconditionalPasteBlockBefore", "Paste Block")
    nmap(",PB", "<Plug>UnconditionalPasteJaggedBefore", "Paste Jagged")
    nmap(",Pi", "<Plug>UnconditionalPasteInlinedBefore", "Paste Inline")
    nmap(",Pl", "<plug>UnconditionalPasteLineBefore", "Paste Line")
    nmap(",PS", "<Plug>UnconditionalPasteParagraphedBefore", "Paste Paragraph")
    nmap(",Ps", "<Plug>UnconditionalPasteSpacedBefore", "Paste Spaced")
    nnoremap(",Pu", "P`]l", "Paste No Move")

    m.name(",p", "Paste")
    nmap(",pb", "<Plug>UnconditionalPasteBlockAfter", "Paste Block")
    nmap(",pB", "<Plug>UnconditionalPasteJaggedAfter", "Paste Jagged")
    nmap(",pi", "<Plug>UnconditionalPasteInlinedAfter", "Paste Inline")
    nmap(",pl", "<plug>UnconditionalPasteLineAfter", "Paste Line")
    nmap(",pS", "<Plug>UnconditionalPasteParagraphedAfter", "Paste Paragraph")
    nmap(",ps", "<Plug>UnconditionalPasteSpacedAfter", "Paste Spaced")
    nnoremap(",pu", "p`[h", "Paste No Move")

    m.name(",i", "Insert")
    nnoremap(",iH", "I", "Insert Before Line")
    nnoremap(",ih", "i", "Insert Before")
    nnoremap(",il", "a", "Insert After")
    nnoremap(",iL", "A", "Insert After Line")

    nnoremap(",iK", "ggO", "Insert Above File")
    nnoremap(",ik", "O", "Insert Above")
    nnoremap(",ij", "o", "Insert Below")
    nnoremap(",iJ", "Go", "Insert Below File")

    nmap(",i{", "<Plug>(ninja-insert)a", "Go Insert Left Outside")
    nmap(",i(", "<Plug>(ninja-insert)i", "Go Insert Left Inside")
    nmap(",i)", "<Plug>(ninja-append)i", "Go Insert Right Inside")
    nmap(",i}", "<Plug>(ninja-append)a", "Go Insert Right Outside")

    m.name(",s", "Change Case")
    nmap(",sp", "<Plug>CaserMixedCase", "Pascal Case")
    nmap(",sc", "<Plug>CaserCamelCase", "Camel Case")
    nmap(",ss", "<Plug>CaserSnakeCase", "Snake Case")
    nmap(",su", "<Plug>CaserUpperCase", "Upper Case")
    nmap(",st", "<Plug>CaserTitleCase", "Title Case")
    nmap(",sd", "<Plug>CaserSentenceCase", "Sentance Case")
    nmap(",s<space>", "<Plug>CaserSpaceCase", "Space Case")
    nmap(",sk", "<Plug>CaserKebabCase", "Kebab Case")
    nmap(",sk", "<Plug>CaserTitleKebabCase", "Title Kebab Case")
    nmap(",s.", "<Plug>CaserDotCase", "Dot Case")
    xmap(",fp", "<Plug>CaserVMixedCase", "Pascal Case")
    xmap(",fc", "<Plug>CaserVCamelCase", "Camel Case")
    xmap(",f_", "<Plug>CaserVSnakeCase", "Snake Case")
    xmap(",fu", "<Plug>CaserVUpperCase", "Upper Case")
    xmap(",ft", "<Plug>CaserVTitleCase", "Title Case")
    xmap(",fs", "<Plug>CaserVSentenceCase", "Sentance Case")
    xmap(",f<space>", "<Plug>CaserVSpaceCase", "Space Case")
    xmap(",f-", "<Plug>CaserVKebabCase", "Kebab Case")
    xmap(",fk", "<Plug>CaserVTitleKebabCase", "Title Case")
    xmap(",f.", "<Plug>CaserVDotCase", "Dot Case")

m.name("<leader>", "Leader")
nnoremap("<leader><leader>", "<cmd>e #<cr>", "Last File")
nnoremap("<leader>.", "<cmd>Telescope lsp_code_actions theme=get_cursor<CR>", "Code Actions")
xnoremap("<leader>.", "<cmd>Telescope lsp_range_code_actions theme=get_cursor<CR>", "Code Actions")
    m.name("<leader>/", "Related Files")
    nnoremap("<leader>/", "<cmd>Z<cr>", "Alternate File")
    nnoremap("<leader>/r", "<cmd>Ereadme<cr>", "Readme")
        m.name("<leader>/n", "New File")
        nnoremap("<leader>/nr", [[<cmd>Ereadme<cr>]], "Readme")

    m.name("<leader>f", "Telescope")
    nnoremap("<leader>f/", "<cmd>Telescope search_history<cr>", "Search History")
    nnoremap("<leader>f;", "<cmd>Telescope command_history<cr>", "Search History")
    nnoremap("<leader>fs", "<cmd>Telescope lsp_workspace_symbols<cr>", "Symbols")
    nnoremap("<leader>fS", "<cmd>Telescope lsp_document_symbols<cr>", "Symbols (buffer)")
    nnoremap("<leader>fE", "<cmd>Telescope lsp_document_diagnostics<cr>", "Errors (buffer)")
    nnoremap("<leader>fe", "<cmd>Telescope lsp_workspace_diagnostics<cr>", "Errors")
    nnoremap("<leader>fB", "<cmd>Telescope buffers only_cwd=true<cr>", "Buffers (cwd)")
    nnoremap("<leader>fb", "<cmd>Telescope buffers<cr>", "Buffers")
    nnoremap("<leader>fC", "<cmd>Telescope git_bcommits<cr>", "Commits (buffer)")
    nnoremap("<leader>fc", "<cmd>Telescope git_commits<cr>", "Git Commits")
    nnoremap("<leader>fF", "<cmd>lua require('telescope.builtin').find_files({find_command={'fd', '-I'}})<cr>", "Files (non git)")
    nnoremap("<leader>ff", "<cmd>call v:lua.project_files()<cr>", "Find Files")
    nnoremap("<leader>fG", "<cmd>Gitsigns setqflist<cr><cmd>Telescope quickfix<cr>", "Git Changes")
    nnoremap("<leader>fg", "<cmd>Telescope git_status<cr>", "Git Status")
    nnoremap("<leader>fj", "<cmd>Telescope jumplist<cr>", "Jumps")
    nnoremap("<leader>fl", "<cmd>Telescope current_buffer_fuzzy_find<cr>", "Fuzzy Line")
    nnoremap("<leader>fL", '<cmd>Telescope grep_string only_sort_text=true search=""<cr>', "Fuzzy Line (Project)")
    nnoremap("<leader>fm", "<cmd>Telescope marks<cr>", "Marks")
    nnoremap("<leader>fn", "<cmd>TodoTelescope<cr>", "Todo Items")
    nnoremap("<leader>fi", "<cmd>Telescope media_files<cr>", "Images (and other media)")
    nnoremap("<leader>fo", "<cmd>Telescope oldfiles<cr>", "Old Files")
    nnoremap("<leader>fq", "<cmd>Telescope quickfix<cr>", "QuickFix")
    nnoremap("<leader>fr", "<cmd>Telescope live_grep<cr>", "Grep")
    nnoremap("<leader>fR", [["<cmd> Telescope grep_string search=" . input("Grep For > ") . "<CR>"]], "Fast Grep (with regex)", "expr")
    nnoremap("<leader>fV", [["<cmd> noautocmd vimgrep /" . input("What would you like to vimgrep? > ") . "/gj " . input("In what files? > ") . "<cr><cmd>Telescope quickfix<cr>"]], "Vim Grep (file select)", "expr")
    nnoremap("<leader>fv", [["<cmd> noautocmd vimgrep /" . input("What would you like to vimgrep? > ") . "/gj **/* <cr><cmd>Telescope quickfix<cr>"]], "Vim Grep", "expr")
    nnoremap("<leader>fx", "<cmd>Telescope file_browser<cr>", "File Browser")
    nnoremap("<leader>fX", "<cmd>lua require'telescope.builtin'.file_browser{cwd=require'telescope.utils'.buffer_dir()}<cr>", "File Browser (Relative)")
    nnoremap("<leader>fI", "<cmd>lua require'telescope.builtin'.symbols{sources={'julia'}}<cr>", "Insert Symbols")

    m.name("<leader>r", "Refactor")
    xnoremap("<leader>rf", "<cmd>lua require('refactoring').refactor('Extract Function')<cr>", "Extract Function")
    xnoremap("<leader>rF", "<cmd>lua require('refactoring').refactor('Extract Function to File')<cr>", "Extract Function")
    xnoremap("<leader>rv", "<cmd>lua require('refactoring').refactor('Extract Variable')<cr>", "Extract Variable")
    xnoremap("<leader>ri", "<cmd>lua require('refactoring').refactor('Inline Variable')<cr>", "Inline Variable")

    m.name("<leader>w", "Window Managment")
    nnoremap("<leader>w<leader>", "<c-w>p", "Jump To Last Split")
    nnoremap("<leader>wo", "<c-w>o", "Clean Up Windows")
    nnoremap("<leader>wO", "<cmd>BDelete hidden<cr>", "Close All Hidden Buffers")
    nnoremap("<leader>wf", "<c-w>w", "Focus Floating Window")
    nnoremap("<leader>wd", "<cmd>bdelete<cr>", "Delete the current buffer")
    nnoremap("<leader>wD", "<cmd>tabclose<cr>", "Close the Current Tab")
    nnoremap("<leader>w<bs>", "<c-w>c", "Close Window")
    nnoremap("<leader>w<cr>", "<c-w>v", "Open Window")
    nnoremap("<leader>wx", "<c-w>s", "Horizontal Split")
    nnoremap("<leader>wv", "<c-w>v", "Vertical Split")
    nnoremap("<leader>wn", "<C-W>n", "Open New Window")
    nnoremap("<leader>w=", "<c-w>=", "Equal Size")
    nnoremap("<leader>wh", "<c-w>H", "Move Far Left")
    nnoremap("<leader>wj", "<c-w>J", "Move Far Down")
    nnoremap("<leader>wk", "<c-w>K", "Move Far Up")
    nnoremap("<leader>wl", "<c-w>L", "Move Far Right")
    nnoremap("<leader>wc", "<c-w>c", "Close Window")
    nnoremap("<leader>wq", "<c-w>c", "Close Window")

    m.name("<leader>g", "Git")
    nnoremap("<leader>gg", "<cmd>silent !kitty @ launch --cwd=current --type=window --window-title 'LazyGit' lazygit<cr>", "LazyGit")
    nnoremap("<leader>gG", "<cmd>silent !kitty @ launch --cwd=current --type=tab --tab-title 'LazyGit' lazygit<cr>", "LazyGit")
    nnoremap("<leader>ga", "<cmd>lua require'gitsigns'.blame_line({full=true})<CR>", "Blame Line")
    nnoremap("<leader>gA", "<cmd>Gitsigns toggle_current_line_blame<CR>", "Blame Toggle")

    nnoremap("<leader>gb", "<cmd>Telescope git_branches<cr>", "Branches")
    nnoremap("<leader>gC", "<cmd>Telescope git_bcommits<cr>", "Commits (buffer)")
    nnoremap("<leader>gc", "<cmd>Telescope git_commits<cr>", "Commits")
    nnoremap("<leader>gq", "<cmd>Gitsigns setqflist<cr><cmd>let g:panelRepeat='q'<cr><cmd>Trouble quickfix<cr>", "Send diffs to qf")

    nnoremap("<leader>gp", "<cmd>Gitsigns preview_hunk<CR>", "Hunk Preview")
    nnoremap("<leader>gr", "<cmd>Gitsigns reset_hunk<CR>", "Hunk Reset")
    nnoremap("<leader>gR", "<cmd>Gitsigns reset_buffer<CR>", "Reset Buffer")
    nnoremap("<leader>gS", "<cmd>Gitsigns stage_buffer<CR>", "Stage File")
    nnoremap("<leader>gs", "<cmd>Gitsigns stage_hunk<CR>", "Hunk Stage")
    nnoremap("<leader>gv", "<cmd>Gitsigns select_hunk<CR>", "Select Current Hunk")
    xnoremap("<leader>gs", "<cmd>lua require'gitsigns'.stage_hunk({vim.fn.line('.'), vim.fn.line('.')})", "Stage Hunks in Range")
    xnoremap("<leader>gr", "<cmd>lua require'gitsigns'.reset_hunk({vim.fn.line('.'), vim.fn.line('.')})", "Reset Hunks in Range")

        m.name("<leader>gd", "Git Diff")
        nnoremap("<leader>gdl", "<cmd>call v:lua.diff_repeat()<cr>", "Repeat Last Diff")
        nnoremap("<leader>gdd", "<cmd>call v:lua.diff_repeat()<cr>", "Repeat Last Diff")

        nnoremap("<leader>gdD", "<cmd>let g:DiffviewLast='DiffviewOpen'<cr><cmd>DiffviewOpen<CR>", "Git Diff Viewer")
        nnoremap("<leader>gdc", "<cmd>call v:lua.git_commits_onechange()<cr>", "View The Diff of a Commit")
        nnoremap("<leader>gdC", "<cmd>call v:lua.git_commits_againsthead()<cr>", "Diff Against a Commit")
        nnoremap("<leader>gdb", "<cmd>call v:lua.git_branch_dif()<cr>", "Diff Against a Branch")
        nnoremap("<leader>gdB", "<cmd>call v:lua.git_branch_mergebase()<cr>", "View The Diff of a Branch")

        nnoremap("<leader>gdh", "<cmd>let g:DiffviewLast='DiffviewFileHistory'<cr><cmd>DiffviewFileHistory<CR>", "View File History")
        nnoremap("<leader>gdH", [["<cmd>let g:DiffviewLast='DiffviewFileHistory" . getcwd() . "'<cr><cmd>DiffviewFileHistory" . getcwd() . "<CR>"]], "View Directory History", "expr")

        m.name("<leader>gh", "GitHub")
        nnoremap("<leader>ghe", [["<cmd>RepoEdit git@github.com:" . input("What repo would you like to browse > ") . "<cr>"]], "Browse Repo", "expr")
        nnoremap("<leader>ghi", "<cmd>Telescope gh issues<cr>", "Search Issues")
        nnoremap("<leader>ghp", "<cmd>Telescope gh pull_request<cr>", "Search Pull Requests")
        nnoremap("<leader>ghg", "<cmd>Telescope gh gist<cr>", "Search Gists")
        nnoremap("<leader>ghr", "<cmd>Telescope gh run<cr>", "Search GH Runs")
        m.name("<leader>g,", "Git Settings")
        nnoremap("<leader>g,b", "<cmd>call v:lua.gitsign_change_base()<cr>", "Change Gitsigns Base")
        nnoremap("<leader>g,B", "<cmd>call v:lua.gitsign_bchange_base()<cr>", "Change Gitsigns Base")

    m.name("<leader>p", "Preview")
    nnoremap("<leader>pa", "<cmd>lua require'gitsigns'.blame_line({full=true})<CR>", "Blame Line")
    nnoremap("<leader>pp", "<Cmd>lua vim.lsp.buf.hover({ focusable = false})<CR>", "Documentation")
    nnoremap("<leader>ps", "<cmd>lua vim.lsp.buf.signature_help({ focusable = false})<CR>", "Signature")
    nnoremap("<leader>pd", "<cmd>lua PeekDefinition()<CR>", "Definition")
    nnoremap("<leader>pE", "<cmd>call v:lua.toggle_diagnostics()<cr>", "Toggle Diagnostics Shown")
    nnoremap("<leader>pe", "<cmd>lua vim.diagnostic.open_float(0, {border='single', scope='line', source='always'})<CR>", "Diagnostics")
    nnoremap("<leader>pW", "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>", "Workspace Directory")
    nnoremap("<leader>pg", "<cmd>lua require'gitsigns'.preview_hunk()<CR>", "Hunk Preview")
    nnoremap("<leader>pw", "<cmd>MatchupWhereAmI??<cr>", "Preview Location")

    m.name("<leader>v", "View Panels")
    nmap("v:lua.commandRepeat('<leader>v', 'panelRepeat')", "Repeat Panel", "expr")
    nnoremap("<leader>ve", "<cmd>let g:panelRepeat='e'<cr><cmd>TroubleToggle lsp_workspace_diagnostics<CR>", "Error List (Workspace)")
    nnoremap("<leader>vE", "<cmd>let g:panelRepeat='E'<cr><cmd>TroubleToggle lsp_document_diagnostics<CR>", "Error List")
    nnoremap("<leader>vq", "<cmd>let g:panelRepeat='q'<cr><cmd>TroubleToggle quickfix<CR>", "QuickFix List")
    nnoremap("<leader>vn", "<cmd>let g:panelRepeat='n'<cr><cmd>TodoTrouble<cr>", "Todo List")
    nnoremap("<leader>vg", "<cmd>let g:panelRepeat='g'<cr><cmd>DiffviewOpen<CR>", "Git")
    nnoremap("<leader>vu", "<cmd>let g:panelRepeat='u'<cr><cmd>UndotreeToggle<CR>", "Undo Tree")

    m.name("<leader>q", "Quickfix List")
    nnoremap("<leader>ql", "<cmd>cnewer<cr>", "Newer List")
    nnoremap("<leader>qh", "<cmd>colder<cr>", "Older List")
    nmap("<leader>qq", "<cmd>let g:panelRepeat='q'<cr><cmd>TroubleToggle quickfix<CR>", "QuickFix List")
    nnoremap("<leader>qn", "<cmd>TodoQuickFix<cr><let g:panelRepeat='q'<cr><cmd>Trouble quickfix<cr>", "Populate with todo items")
    nnoremap("<leader>q2", [["<cmd> noautocmd vimgrep /" . input("What would you like to vimgrep? > ") . "/gj **/* <cr><cmd>let g:panelRepeat='q'<cr><cmd>Trouble quickfix<cr>"]], "Populate With VimGrep (file select)", "expr")
    nnoremap("<leader>q2", [["<cmd> noautocmd vimgrep /" . input("What would you like to vimgrep? > ") . "/gj " . input("In what files? > ") . "<cr><cmd>let g:panelRepeat='q'<cr><cmd>Trouble quickfix<cr>"]], "Populate With VimGrep", "expr")

    m.name("<leader>e", "Errors")
    nnoremap("<leader>ep", "<cmd>call v:lua.toggle_diagnostics()<cr>", "Toggle Diagnostics Shown")
    nnoremap("<leader>er", "<cmd>TroubleRefresh<cr>", "Refresh Errors")
    nnoremap("<leader>ee", "<cmd>let g:panelRepeat='e'<cr><cmd>TroubleToggle lsp_workspace_diagnostics<CR>", "Error List")
    nnoremap("<leader>eE", "<cmd>let g:panelRepeat='E'<cr><cmd>TroubleToggle lsp_document_diagnostics<CR>", "Error List (buffer)")
    nnoremap("<leader>en", "<cmd>let g:panelRepeat='n'<cr><cmd>TodoTrouble<cr>", "Todo List")

    m.name("<leader>t", "Terminal")
    nnoremap("<leader>tt", "<cmd>silent !kittyPersistent normterm<cr>", "Normal Terminal")
    nnoremap("<leader>ti", [[<cmd>silent exe "!kittyrepl replterm " . b:replCommand<cr>]], "REPL Terminal")
    nnoremap("<leader>td", [[<cmd>silent exe "!kittyPersistent debugterm " . b:debugCommand<cr>]], "Debug Terminal")
    nnoremap("<leader>tm", "<cmd>silent !kittyPersistent maketerm<cr>", "Building Terminal")

    m.name("<leader>m", "Make")
    m.name("<leader>u", "Unit Tests")
    m.name("<leader>d", "Debugging")

    m.name("<leader>r", "Refactoring")
    nnoremap("<leader>rr", "<cmd>lua vim.lsp.buf.rename()<CR>", "Rename (LSP)")
    nmap("<leader>rf", "zib<cmd>lua require('refactoring').refactor('Extract Function')<cr>", "Extract Function")
    nmap("<leader>rF", "zib<cmd>lua require('refactoring').refactor('Extract Function to File')<cr>", "Extract Function")
    nmap("<leader>rv", "zi,<cmd>lua require('refactoring').refactor('Extract Variable')<cr>", "Extract Variable")
    nmap("<leader>ri", "zi,<cmd>lua require('refactoring').refactor('Inline Variable')<cr>", "Inline Variable")

    m.name("<leader>,", "Settings")
    nnoremap("<leader>,,", "<cmd>Telescope vim_options<cr>", "Vim Options")
    nnoremap("<leader>,s", "<cmd>set spell!<cr>", "Toggle Spelling")
    nnoremap("<leader>,k", "<cmd>Telescope keymaps<cr>", "Keymaps")
    nnoremap("<leader>,C", "<cmd>Telescope colorscheme<cr>", "Color Schemes")
    nnoremap("<leader>,c", "<cmd>Telescope highlights<cr>", "Highlight Groups")
    nnoremap("<leader>,a", "<cmd>Telescope autocommands<cr>", "AutoCommands")
    nnoremap("<leader>,f", "<cmd>Telescope filetypes<cr>", "FileTypes")
    nnoremap("<leader>,h", "<cmd>Telescope help_tags<cr>", "Help Tags")
    nnoremap("<leader>,m", "<cmd>Telescope man_pages<cr>", "Man Pages")
    nnoremap("<leader>,d", "<cmd>call v:lua.toggle_diagnostics()<cr>", "Toggle Diagnostics Shown")
    nnoremap("<leader>,w", "<cmd>set wrap!<cr>", "Toggle Text Wraping")
    nnoremap("<leader>,/", "<cmd>let @/=''<cr>", "Clear Search")

nnoremap("<leader>k", [[":silent !kitty @ launch --type=tab --tab-title 'Kak %:t' kak %:p +" . line(".") . ":" . col(".") . "<cr>"]], "Open file in Kak", "expr")
nnoremap("<leader>z", "<cmd>ZenMode<cr>", "Zen Mode")

m.name("[", "Backward Leader")
nnoremap("[[", "<cmd>let g:dirJumps='s'<cr>m`<cmd>TSTextobjectGotoPreviousStart @function.outer<cr>zz", "Scope")
nnoremap("[]", "<cmd>let g:dirJumps='S'<cr>m`<cmd>TSTextobjectGotoPreviousEnd @function.outer<cr>zz", "Scope")
nnoremap("[s", "<cmd>let g:dirJumps='s'<cr>m`<cmd>TSTextobjectGotoPreviousStart @function.outer<cr>zz", "Scope")
nnoremap("[S", "<cmd>let g:dirJumps='S'<cr>m`<cmd>TSTextobjectGotoPrevioutEnd @function.outer<cr>zz", "Scope")
nnoremap("[,", "<cmd>let g:dirJumps=','<cr>m`<cmd>TSTextobjectGotoPreviousStart @parameter.inner<cr>zz", "Parameter")
nnoremap("[b", "<cmd>let g:dirJumps='b'<cr>m`<cmd>TSTextobjectGotoPreviousStart @block.outer<cr>zz", "Block")
nnoremap("[<", "<cmd>let g:dirJumps='<'<cr>m`<cmd>TSTextobjectGotoPreviousEnd @parameter.inner<cr>zz", "Parameter")
nnoremap("[B", "<cmd>let g:dirJumps='B'<cr>m`<cmd>TSTextobjectGotoPreviousEnd @block.outer<cr>zz", "Block")
nnoremap("[h", [[&diff ? "[czz<cmd>let g:dirJumps='h'<cr>m`" : "<cmd>lua require'gitsigns'.prev_hunk()<cr>zz<cmd>let g:dirJumps='h'<cr>m`"]], "Hunk", "expr")
nnoremap("[q", "<cmd>let g:dirJumps='q'<cr>m`<cmd>try<bar>cprevious<bar>catch/E553/<bar>clast<bar>endtry<cr>zz", "QuickFix Entry")
nnoremap("[/", "<cmd>let g:dirJumps='search'<cr>m`Nzz", "Search Result")
nnoremap("[p", "<cmd>let g:dirJumps='p'<cr>{zz", "Paragraph")
nnoremap("[w", "<cmd>let g:dirJumps='w'<cr>b", "Word")
nnoremap("[e", "<cmd>let g:dirJumps='e'<cr>ge", "Word End")
-- nmap("[$w", "<cmd>let g:dirJumps='$w'<cr><plug>WordMotion_b", "Sub-Word")
-- nmap("[$e", "<cmd>let g:dirJumps='$e'<cr><plug>WordMotion_ge", "Sub-Word End")
nnoremap("[d", "<cmd>lua vim.diagnostic.goto_prev({ float = {border='single', scope='cursor', source='always'}})<CR>zz<cmd>let g:dirJumps='e'<cr>m`", "Diagnostics")
    m.name("[D", "Diagnostaic Type")
    nnoremap("[Dn", "<cmd>lua vim.diagnostic.goto_prev({severity='Error',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Da'<cr>m`", "Error")
    nnoremap("[De", "<cmd>lua vim.diagnostic.goto_prev({severity='Warn',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Dr'<cr>m`", "Warn")
    nnoremap("[Di", "<cmd>lua vim.diagnostic.goto_prev({severity='Info',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Ds'<cr>m`", "Info")
    nnoremap("[Do", "<cmd>lua vim.diagnostic.goto_prev({severity='Hint',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Dt'<cr>m`", "Hint")
xnoremap("[[", "<cmd>let g:dirJumps='s'<cr>m`<cmd>TSTextobjectGotoPreviousStart @function.outer<cr>zz", "Scope")
xnoremap("[]", "<cmd>let g:dirJumps='S'<cr>m`<cmd>TSTextobjectGotoPreviousEnd @function.outer<cr>zz", "Scope")
xnoremap("[s", "<cmd>let g:dirJumps='s'<cr>m`<cmd>TSTextobjectGotoPreviousStart @function.outer<cr>zz", "Scope")
xnoremap("[S", "<cmd>let g:dirJumps='S'<cr>m`<cmd>TSTextobjectGotoPrevioutEnd @function.outer<cr>zz", "Scope")
xnoremap("[,", "<cmd>let g:dirJumps=','<cr>m`<cmd>TSTextobjectGotoPreviousStart @parameter.inner<cr>zz", "Parameter")
xnoremap("[b", "<cmd>let g:dirJumps='b'<cr>m`<cmd>TSTextobjectGotoPreviousStart @block.outer<cr>zz", "Block")
xnoremap("[<", "<cmd>let g:dirJumps='<'<cr>m`<cmd>TSTextobjectGotoPreviousEnd @parameter.inner<cr>zz", "Parameter")
xnoremap("[B", "<cmd>let g:dirJumps='B'<cr>m`<cmd>TSTextobjectGotoPreviousEnd @block.outer<cr>zz", "Block")
xnoremap("[h", [[&diff ? "[czz<cmd>let g:dirJumps='h'<cr>m`" : "<cmd>lua require'gitsigns'.prev_hunk()<cr>zz<cmd>let g:dirJumps='h'<cr>m`"]], "Hunk", "expr")
xnoremap("[q", "<cmd>let g:dirJumps='q'<cr>m`<cmd>try<bar>cprevious<bar>catch/E553/<bar>clast<bar>endtry<cr>zz", "QuickFix Entry")
xnoremap("[/", "<cmd>let g:dirJumps='search'<cr>m`Nzz", "Search Result")
xnoremap("[p", "<cmd>let g:dirJumps='p'<cr>{zz", "Paragraph")
xnoremap("[d", "<cmd>lua vim.diagnostic.goto_prev({ float = {border='single', scope='cursor', source='always'}})<CR>zz<cmd>let g:dirJumps='e'<cr>m`", "Diagnostics")
    xnoremap("[Dn", "<cmd>lua vim.diagnostic.goto_prev({severity='Error',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Da'<cr>m`", "Error")
    xnoremap("[De", "<cmd>lua vim.diagnostic.goto_prev({severity='Warn',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Dr'<cr>m`", "Warn")
    xnoremap("[Di", "<cmd>lua vim.diagnostic.goto_prev({severity='Info',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Ds'<cr>m`", "Info")
    xnoremap("[Do", "<cmd>lua vim.diagnostic.goto_prev({severity='Hint',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Dt'<cr>m`", "Hint")

m.name("]", "Forward Leader")
nnoremap("]]", "<cmd>let g:dirJumps='s'<cr>m`<cmd>TSTextobjectGotoNextStart @function.outer<cr>zz", "Scope")
nnoremap("][", "<cmd>let g:dirJumps='S'<cr>m`<cmd>TSTextobjectGotoNextEnd @function.outer<cr>zz", "Scope")
nnoremap("]s", "<cmd>let g:dirJumps='s'<cr>m`<cmd>TSTextobjectGotoNextStart @function.outer<cr>zz", "Scope")
nnoremap("]S", "<cmd>let g:dirJumps='S'<cr>m`<cmd>TSTextobjectGotoNextEnd @function.outer<cr>zz", "Scope")
nnoremap("],", "<cmd>let g:dirJumps=','<cr>m`<cmd>TSTextobjectGotoNextStart @parameter.inner<cr>zz", "Parameter")
nnoremap("]<", "<cmd>let g:dirJumps='<'<cr>m`<cmd>TSTextobjectGotoNextEnd @parameter.inner<cr>zz", "Parameter (end)")
nnoremap("]b", "<cmd>let g:dirJumps='b'<cr>m`<cmd>TSTextobjectGotoNextStart @block.outer<cr>zz", "Block")
nnoremap("]B", "<cmd>let g:dirJumps='B'<cr>m`<cmd>TSTextobjectGotoNextEnd @block.outer<cr>zz", "Block (end)")
nnoremap("]h", [[&diff?"]czz<cmd>let g:dirJumps='h'<cr>m`":"<cmd>luarequire'gitsigns'.next_hunk()<cr>zz<cmd>let g:dirJumps='h'<cr>m`"]], "Hunk", "expr")
nnoremap("]q", "<cmd>let g:dirJumps='q'<cr>m`<cmd>try<bar>cnext<bar>catch/E553/<bar>cfirst<bar>endtry<cr>zz", "QuickFix Entry")
nnoremap("]/", "<cmd>let g:dirJumps='search'<cr>m`nzz", "Search Result")
nnoremap("]p", "<cmd>let g:dirJumps='p'<cr>}zz", "Paragraph")
nnoremap("]w", "<cmd>let g:dirJumps='w'<cr>w", "Word")
nnoremap("]e", "<cmd>let g:dirJumps='e'<cr>e", "Word End")
-- nmap("]$w", "<cmd>let g:dirJumps='$w'<cr><plug>WordMotion_w", "Sub-Word")
-- nmap("]$e", "<cmd>let g:dirJumps='$e'<cr><plug>WordMotion_e", "Sub-Word End")
nnoremap("]d", "<cmd>lua vim.diagnostic.goto_next({float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='d'<cr>m`", "Diagnostics")
    m.name("]D", "Diagnostaic Type")
    nnoremap("]Dn", "<cmd>lua vim.diagnostic.goto_next({severity='Error',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Da'<cr>m`", "Error")
    nnoremap("]De", "<cmd>lua vim.diagnostic.goto_next({severity='Warn',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Dr'<cr>m`", "Warn")
    nnoremap("]Di", "<cmd>lua vim.diagnostic.goto_next({severity='Info',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Ds'<cr>m`", "Info")
    nnoremap("]Do", "<cmd>lua vim.diagnostic.goto_next({severity='Hint',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Dt'<cr>m`", "Hint")
xnoremap("]]", "<cmd>let g:dirJumps='s'<cr>m`<cmd>TSTextobjectGotoNextStart @function.outer<cr>zz", "Scope")
xnoremap("][", "<cmd>let g:dirJumps='S'<cr>m`<cmd>TSTextobjectGotoNextEnd @function.outer<cr>zz", "Scope")
xnoremap("]s", "<cmd>let g:dirJumps='s'<cr>m`<cmd>TSTextobjectGotoNextStart @function.outer<cr>zz", "Scope")
xnoremap("]S", "<cmd>let g:dirJumps='S'<cr>m`<cmd>TSTextobjectGotoNextEnd @function.outer<cr>zz", "Scope")
xnoremap("],", "<cmd>let g:dirJumps=','<cr>m`<cmd>TSTextobjectGotoNextStart @parameter.inner<cr>zz", "Parameter")
xnoremap("]<", "<cmd>let g:dirJumps='<'<cr>m`<cmd>TSTextobjectGotoNextEnd @parameter.inner<cr>zz", "Parameter (end)")
xnoremap("]b", "<cmd>let g:dirJumps='b'<cr>m`<cmd>TSTextobjectGotoNextStart @block.outer<cr>zz", "Block")
xnoremap("]B", "<cmd>let g:dirJumps='B'<cr>m`<cmd>TSTextobjectGotoNextEnd @block.outer<cr>zz", "Block (end)")
xnoremap("]h", [[&diff?"]czz<cmd>let g:dirJumps='h'<cr>m`":"<cmd>luarequire'gitsigns'.next_hunk()<cr>zz<cmd>let g:dirJumps='h'<cr>m`"]], "Hunk", "expr")
xnoremap("]q", "<cmd>let g:dirJumps='q'<cr>m`<cmd>try<bar>cnext<bar>catch/E553/<bar>cfirst<bar>endtry<cr>zz", "QuickFix Entry")
xnoremap("]/", "<cmd>let g:dirJumps='search'<cr>m`nzz", "Search Result")
xnoremap("]p", "<cmd>let g:dirJumps='p'<cr>}zz", "Paragraph")
xnoremap("]d", "<cmd>lua vim.diagnostic.goto_next({float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='d'<cr>m`", "Diagnostics")
    xnoremap("]Dn", "<cmd>lua vim.diagnostic.goto_next({severity='Error',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Da'<cr>m`", "Error")
    xnoremap("]De", "<cmd>lua vim.diagnostic.goto_next({severity='Warn',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Dr'<cr>m`", "Warn")
    xnoremap("]Di", "<cmd>lua vim.diagnostic.goto_next({severity='Info',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Ds'<cr>m`", "Info")
    xnoremap("]Do", "<cmd>lua vim.diagnostic.goto_next({severity='Hint',float={border='single',scope='cursor',source='always'}})<CR>zz<cmd>let g:dirJumps='Dt'<cr>m`", "Hint")

-- TODO : Movement always infront of dirJump setting, so works in opperator pending mode
-- TODO : Merge with in next/in last op bindings, have logic for n always following dirJumps
-- TODO : Or have a new variable for operator only ones
-- TODO : Make bindings for n,N for visual, operator
-- TODO : Make gn,gN bindings

m.name("<localleader>", "Local Leader")

-- Git Diff Bindings
if vim.api.nvim_win_get_option(0, "diff") then
    nnoremap("<leader>[", "<cmd>diffget LOCAL<cr>", "Take From Local Change")
    nnoremap("<leader>]", "<cmd>diffget REMOTE<cr>", "Take From Remote Change")
    nnoremap("<leader><leader>", "<cmd>diffget BASE<cr>", "Take From Base" )
end

-- Visual Bindings

m.xname("a", "Around")
xnoremap("ah", ":<c-u>Gitsigns selct_hunk<cr>", "Git Hunk")
xnoremap("aB", ":<c-u>TSTextobjectSelect @block.outer<cr>", "Block")
xnoremap("ac", ":<c-u>TSTextobjectSelect @conditional.outer<cr>", "Conditional")
xnoremap("a,", ":<c-u>TSTextobjectSelect @parameter.outer<cr>", "Parameter")
xnoremap("ad", ":<c-u>TSTextobjectSelect @comment.outer<cr>", "Comment")
xnoremap("af", ":<c-u>TSTextobjectSelect @function.outer<cr>", "Function")
xnoremap("aF", ":<c-u>TSTextobjectSelect @call.outer<cr>", "Function")
xnoremap("ao", ":<c-u>TSTextobjectSelect @class.outer<cr>", "Class")
xnoremap("av", "<cmd>exec 'normal! HVL'<cr>", "Select Viewport")
    m.xname("a]", "Around Next")
    xnoremap("a]s", ":<c-u>call v:lua.mapped_targets(v:count, ')', 'as')<cr>", "Sentance")
    xnoremap("a]w", ":<c-u>call v:lua.mapped_targets(v:count, 'w', 'aw')<cr>", "Word")
    xnoremap("a]W", ":<c-u>call v:lua.mapped_targets(v:count, 'W', 'aW')<cr>", "Word")
    xnoremap("a]$w", ":<c-u>call v:lua.mapped_targets(v:count, '$w', 'a$w')<cr>", "Sub Word")
    xnoremap("a]p", ":<c-u>call v:lua.paragraph_targets(v:count, 1)<cr>", "Paragraph")
    xnoremap("a]h", ":<c-u>call v:lua.git_target(v:count, 'true')<cr>", "Git Hunk")
    xnoremap("a]B", ":<c-u>call v:lua.ts_target(v:count, '@block.outer')<cr>", "Block")
    xnoremap("a]c", ":<c-u>call v:lua.ts_target(v:count, '@conditional.outer')<cr>", "Conditional")
    xnoremap("a],", ":<c-u>call v:lua.ts_target(v:count, '@parameter.outer')<cr>", "Parameter")
    xnoremap("a]d", ":<c-u>call v:lua.ts_target(v:count, '@comment.outer')<cr>", "Comment")
    xnoremap("a]f", ":<c-u>call v:lua.ts_target(v:count, '@function.outer')<cr>", "Function")
    xnoremap("a]F", ":<c-u>call v:lua.ts_target(v:count, '@call.outer')<cr>", "Function")
    xnoremap("a]o", ":<c-u>call v:lua.ts_target(v:count, '@class.outer')<cr>", "Class")
    m.xname("a[", "Around Previous")
    xnoremap("a[s", ":<c-u>call v:lua.mapped_targets_back(v:count, '(', 'g(', 'as')<cr>", "Sentance")
    xnoremap("a[w", ":<c-u>call v:lua.mapped_targets_back(v:count, 'b', 'ge', 'aw')<cr>", "Word")
    xnoremap("a[W", ":<c-u>call v:lua.mapped_targets_back(v:count, 'B', 'gE', 'aW')<cr>", "Word")
    xnoremap("a[$w", ":<c-u>call v:lua.mapped_targets_back(v:count, '$ge', '$b', 'a$w')<cr>", "Sub Word")
    xnoremap("a[p", ":<c-u>call v:lua.paragraph_targets_back(v:count, 1)<cr>", "Paragraph")
    xnoremap("a[h", ":<c-u>call v:lua.git_target(v:count, 'false')<cr>", "Git Hunk")
    xnoremap("a[B", ":<c-u>call v:lua.ts_target_back(v:count, '@block.outer')<cr>", "Block")
    xnoremap("a[c", ":<c-u>call v:lua.ts_target_back(v:count, '@conditional.outer')<cr>", "Conditional")
    xnoremap("a[,", ":<c-u>call v:lua.ts_target_back(v:count, '@parameter.outer')<cr>", "Parameter")
    xnoremap("a[d", ":<c-u>call v:lua.ts_target_back(v:count, '@comment.outer')<cr>", "Comment")
    xnoremap("a[f", ":<c-u>call v:lua.ts_target_back(v:count, '@function.outer')<cr>", "Function")
    xnoremap("a[F", ":<c-u>call v:lua.ts_target_back(v:count, '@call.outer')<cr>", "Function")
    xnoremap("a[o", ":<c-u>call v:lua.ts_target_back(v:count, '@class.outer')<cr>", "Class")
m.xname("i", "In")
xnoremap("ih", ":<c-u>Gitsigns selct_hunk<cr>", "Git Hunk")
xnoremap("iB", ":<c-u>TSTextobjectSelect @block.inner<cr>", "Block")
xnoremap("ic", ":<c-u>TSTextobjectSelect @conditional.inner<cr>", "Conditional")
xnoremap("i,", ":<c-u>TSTextobjectSelect @parameter.inner<cr>", "Parameter")
xnoremap("id", ":<c-u>TSTextobjectSelect @comment.outer<cr>", "Comment")
xnoremap("if", ":<c-u>TSTextobjectSelect @function.inner<cr>", "Function")
xnoremap("iF", ":<c-u>TSTextobjectSelect @call.inner<cr>", "Function")
xnoremap("io", ":<c-u>TSTextobjectSelect @class.inner<cr>", "Class")
xnoremap("iv", "<cmd>exec 'normal! HVL'<cr>", "Select Viewport")
    m.xname("i[", "In Next")
    xnoremap("i]s", ":<c-u>call v:lua.mapped_targets(v:count, ')', 'is')<cr>", "Sentance")
    xnoremap("i]w", ":<c-u>call v:lua.mapped_targets(v:count, 'w', 'iw')<cr>", "Word")
    xnoremap("i]W", ":<c-u>call v:lua.mapped_targets(v:count, 'W', 'iW')<cr>", "WORD")
    xnoremap("i]$w", ":<c-u>call v:lua.mapped_targets(v:count, '$w', 'i$w')<cr>", "Sub Word")
    xnoremap("i]p", ":<c-u>call v:lua.paragraph_targets(v:count, 0)<cr>", "Paragraph")
    xnoremap("i]h", ":<c-u>call v:lua.git_target(v:count, 'true')<cr>", "Git Hunk")
    xnoremap("i]B", ":<c-u>call v:lua.ts_target(v:count, '@block.inner')<cr>", "Block")
    xnoremap("i]c", ":<c-u>call v:lua.ts_target(v:count, '@conditional.inner')<cr>", "Conditional")
    xnoremap("i],", ":<c-u>call v:lua.ts_target(v:count, '@parameter.inner')<cr>", "Parameter")
    xnoremap("i]d", ":<c-u>call v:lua.ts_target(v:count, '@comment.outer')<cr>", "Comment")
    xnoremap("i]f", ":<c-u>call v:lua.ts_target(v:count, '@function.inner')<cr>", "Function")
    xnoremap("i]F", ":<c-u>call v:lua.ts_target(v:count, '@call.inner')<cr>", "Function")
    xnoremap("i]o", ":<c-u>call v:lua.ts_target(v:count, '@class.inner')<cr>", "Class")
    m.xname("i[", "In Previous")
    xnoremap("i[s", ":<c-u>call v:lua.mapped_targets_back(v:count, '(', 'g(', 'is')<cr>", "Sentance")
    xnoremap("i[w", ":<c-u>call v:lua.mapped_targets_back(v:count, 'b', 'ge', 'iw')<cr>", "Word")
    xnoremap("i[W", ":<c-u>call v:lua.mapped_targets_back(v:count, 'B', 'gE', 'iW')<cr>", "WORD")
    xnoremap("i[$w", ":<c-u>call v:lua.mapped_targets_back(v:count, '$ge', '$b', 'i$w')<cr>", "Sub Word")
    xnoremap("i[p", ":<c-u>call v:lua.paragraph_targets_back(v:count, 0)<cr>", "Paragraph")
    xnoremap("i[h", ":<c-u>call v:lua.git_target(v:count, 'false')<cr>", "Git Hunk")
    xnoremap("i[B", ":<c-u>call v:lua.ts_target_back(v:count, '@block.inner')<cr>", "Block")
    xnoremap("i[c", ":<c-u>call v:lua.ts_target_back(v:count, '@conditional.inner')<cr>", "Conditional")
    xnoremap("i[,", ":<c-u>call v:lua.ts_target_back(v:count, '@parameter.inner')<cr>", "Parameter")
    xnoremap("i[d", ":<c-u>call v:lua.ts_target_back(v:count, '@comment.outer')<cr>", "Comment")
    xnoremap("i[f", ":<c-u>call v:lua.ts_target_back(v:count, '@function.inner')<cr>", "Function")
    xnoremap("i[F", ":<c-u>call v:lua.ts_target_back(v:count, '@call.inner')<cr>", "Function")
    xnoremap("i[o", ":<c-u>call v:lua.ts_target_back(v:count, '@class.inner')<cr>", "Class")

m.oname("a", "Around")
onoremap("ah", ":<c-u>Gitsigns selct_hunk<cr>", "Git Hunk")
onoremap("aB", ":<c-u>TSTextobjectSelect @block.outer<cr>", "Block")
onoremap("ac", ":<c-u>TSTextobjectSelect @conditional.outer<cr>", "Conditional")
onoremap("a,", ":<c-u>TSTextobjectSelect @parameter.outer<cr>", "Parameter")
onoremap("ad", ":<c-u>TSTextobjectSelect @comment.outer<cr>", "Comment")
onoremap("af", ":<c-u>TSTextobjectSelect @function.outer<cr>", "Function")
onoremap("aF", ":<c-u>TSTextobjectSelect @call.outer<cr>", "Function")
onoremap("ao", ":<c-u>TSTextobjectSelect @class.outer<cr>", "Class")
onoremap("av", "<cmd>exec 'normal! HVL'<cr>", "Select Viewport")
    m.oname("a]", "Around Next")
    onoremap("a]s", ":<c-u>call v:lua.mapped_targets(v:count, ')', 'as')<cr>", "Sentance")
    onoremap("a]w", ":<c-u>call v:lua.mapped_targets(v:count, 'w', 'aw')<cr>", "Word")
    onoremap("a]W", ":<c-u>call v:lua.mapped_targets(v:count, 'W', 'aW')<cr>", "Word")
    onoremap("a]$w", ":<c-u>call v:lua.mapped_targets(v:count, '$w', 'a$w')<cr>", "Sub Word")
    onoremap("a]p", ":<c-u>call v:lua.paragraph_targets(v:count, 1)<cr>", "Paragraph")
    onoremap("a]h", ":<c-u>call v:lua.git_target(v:count, 'true')<cr>", "Git Hunk")
    onoremap("a]B", ":<c-u>call v:lua.ts_target(v:count, '@block.outer')<cr>", "Block")
    onoremap("a]c", ":<c-u>call v:lua.ts_target(v:count, '@conditional.outer')<cr>", "Conditional")
    onoremap("a],", ":<c-u>call v:lua.ts_target(v:count, '@parameter.outer')<cr>", "Parameter")
    onoremap("a]d", ":<c-u>call v:lua.ts_target(v:count, '@comment.outer')<cr>", "Comment")
    onoremap("a]f", ":<c-u>call v:lua.ts_target(v:count, '@function.outer')<cr>", "Function")
    onoremap("a]F", ":<c-u>call v:lua.ts_target(v:count, '@call.outer')<cr>", "Function")
    onoremap("a]o", ":<c-u>call v:lua.ts_target(v:count, '@class.outer')<cr>", "Class")
    m.oname("a[", "Around Previous")
    onoremap("a[s", ":<c-u>call v:lua.mapped_targets_back(v:count, '(', 'g(', 'as')<cr>", "Sentance")
    onoremap("a[w", ":<c-u>call v:lua.mapped_targets_back(v:count, 'b', 'ge', 'aw')<cr>", "Word")
    onoremap("a[W", ":<c-u>call v:lua.mapped_targets_back(v:count, 'B', 'gE', 'aW')<cr>", "Word")
    onoremap("a[$w", ":<c-u>call v:lua.mapped_targets_back(v:count, '$ge', '$b', 'a$w')<cr>", "Sub Word")
    onoremap("a[p", ":<c-u>call v:lua.paragraph_targets_back(v:count, 1)<cr>", "Paragraph")
    onoremap("a[h", ":<c-u>call v:lua.git_target(v:count, 'false')<cr>", "Git Hunk")
    onoremap("a[B", ":<c-u>call v:lua.ts_target_back(v:count, '@block.outer')<cr>", "Block")
    onoremap("a[c", ":<c-u>call v:lua.ts_target_back(v:count, '@conditional.outer')<cr>", "Conditional")
    onoremap("a[,", ":<c-u>call v:lua.ts_target_back(v:count, '@parameter.outer')<cr>", "Parameter")
    onoremap("a[d", ":<c-u>call v:lua.ts_target_back(v:count, '@comment.outer')<cr>", "Comment")
    onoremap("a[f", ":<c-u>call v:lua.ts_target_back(v:count, '@function.outer')<cr>", "Function")
    onoremap("a[F", ":<c-u>call v:lua.ts_target_back(v:count, '@call.outer')<cr>", "Function")
    onoremap("a[o", ":<c-u>call v:lua.ts_target_back(v:count, '@class.outer')<cr>", "Class")
m.oname("i", "In")
onoremap("ih", ":<c-u>Gitsigns selct_hunk<cr>", "Git Hunk")
onoremap("iB", ":<c-u>TSTextobjectSelect @block.inner<cr>", "Block")
onoremap("ic", ":<c-u>TSTextobjectSelect @conditional.inner<cr>", "Conditional")
onoremap("i,", ":<c-u>TSTextobjectSelect @parameter.inner<cr>", "Parameter")
onoremap("id", ":<c-u>TSTextobjectSelect @comment.outer<cr>", "Comment")
onoremap("if", ":<c-u>TSTextobjectSelect @function.inner<cr>", "Function")
onoremap("iF", ":<c-u>TSTextobjectSelect @call.inner<cr>", "Function")
onoremap("io", ":<c-u>TSTextobjectSelect @class.inner<cr>", "Class")
onoremap("iv", "<cmd>exec 'normal! HVL'<cr>", "Select Viewport")
    m.oname("i[", "In Next")
    onoremap("i]s", ":<c-u>call v:lua.mapped_targets(v:count, ')', 'is')<cr>", "Sentance")
    onoremap("i]w", ":<c-u>call v:lua.mapped_targets(v:count, 'w', 'iw')<cr>", "Word")
    onoremap("i]W", ":<c-u>call v:lua.mapped_targets(v:count, 'W', 'iW')<cr>", "WORD")
    onoremap("i]$w", ":<c-u>call v:lua.mapped_targets(v:count, '$w', 'i$w')<cr>", "Sub Word")
    onoremap("i]p", ":<c-u>call v:lua.paragraph_targets(v:count, 0)<cr>", "Paragraph")
    onoremap("i]h", ":<c-u>call v:lua.git_target(v:count, 'true')<cr>", "Git Hunk")
    onoremap("i]B", ":<c-u>call v:lua.ts_target(v:count, '@block.inner')<cr>", "Block")
    onoremap("i]c", ":<c-u>call v:lua.ts_target(v:count, '@conditional.inner')<cr>", "Conditional")
    onoremap("i],", ":<c-u>call v:lua.ts_target(v:count, '@parameter.inner')<cr>", "Parameter")
    onoremap("i]d", ":<c-u>call v:lua.ts_target(v:count, '@comment.outer')<cr>", "Comment")
    onoremap("i]f", ":<c-u>call v:lua.ts_target(v:count, '@function.inner')<cr>", "Function")
    onoremap("i]F", ":<c-u>call v:lua.ts_target(v:count, '@call.inner')<cr>", "Function")
    onoremap("i]o", ":<c-u>call v:lua.ts_target(v:count, '@class.inner')<cr>", "Class")
    m.oname("i[", "In Previous")
    onoremap("i[s", ":<c-u>call v:lua.mapped_targets_back(v:count, '(', 'g(', 'is')<cr>", "Sentance")
    onoremap("i[w", ":<c-u>call v:lua.mapped_targets_back(v:count, 'b', 'ge', 'iw')<cr>", "Word")
    onoremap("i[W", ":<c-u>call v:lua.mapped_targets_back(v:count, 'B', 'gE', 'iW')<cr>", "WORD")
    onoremap("i[$w", ":<c-u>call v:lua.mapped_targets_back(v:count, '$ge', '$b', 'i$w')<cr>", "Sub Word")
    onoremap("i[p", ":<c-u>call v:lua.paragraph_targets_back(v:count, 0)<cr>", "Paragraph")
    onoremap("i[h", ":<c-u>call v:lua.git_target(v:count, 'false')<cr>", "Git Hunk")
    onoremap("i[B", ":<c-u>call v:lua.ts_target_back(v:count, '@block.inner')<cr>", "Block")
    onoremap("i[c", ":<c-u>call v:lua.ts_target_back(v:count, '@conditional.inner')<cr>", "Conditional")
    onoremap("i[,", ":<c-u>call v:lua.ts_target_back(v:count, '@parameter.inner')<cr>", "Parameter")
    onoremap("i[d", ":<c-u>call v:lua.ts_target_back(v:count, '@comment.outer')<cr>", "Comment")
    onoremap("i[f", ":<c-u>call v:lua.ts_target_back(v:count, '@function.inner')<cr>", "Function")
    onoremap("i[F", ":<c-u>call v:lua.ts_target_back(v:count, '@call.inner')<cr>", "Function")
    onoremap("i[o", ":<c-u>call v:lua.ts_target_back(v:count, '@class.inner')<cr>", "Class")

imap("<c-a>", "<C-O>^")
imap("<c-e>", "<END>")
cmap("<c-a>", "<HOME>")
cmap("<c-e>", "<END>")

imap("<s-tab>", "<c-d>")
smap("<s-tab>", "<c-d>")

imap("<c-]>", "<plug>luasnip-next-choice")
smap("<c-]>", "<plug>luasnip-next-choice")

imap("<c-space>", "v:lua.cmp_toggle()", "expr")
smap("<c-space>", "v:lua.cmp_toggle()", "expr")

imap("<S-Tab>", "v:lua.s_tab_complete()", "expr")
imap("<Tab>", "v:lua.tab_complete()", "expr")
smap("<S-Tab>", "v:lua.s_tab_complete()", "expr")
smap("<Tab>", "v:lua.tab_complete()", "expr")

inoremap( "<Down>", [[<cmd>lua require("cmp").select_next_item({ behavior = require("cmp").SelectBehavior.Select })<cr>]])
inoremap("<Up>", [[<cmd>lua require("cmp").select_prev_item({ behavior = require("cmp").SelectBehavior.Select })<cr>]])
snoremap( "<Down>", [[<cmd>lua require("cmp").select_next_item({ behavior = require("cmp").SelectBehavior.Select })<cr>]])
snoremap("<Up>", [[<cmd>lua require("cmp").select_prev_item({ behavior = require("cmp").SelectBehavior.Select })<cr>]])
