#!/bin/bash

projectDir=$PWD
docsBuild="$projectDir/docs/make.jl"
docsFile="$projectDir/docs/build/index.html"

julia --threads=auto --project -e '
using Pkg

mktempdir() do p
    cp(joinpath(pwd(), "docs", "Project.toml"), joinpath(p, "Project.toml"))

    Pkg.activate(p)

    Pkg.develop(PackageSpec(path = pwd()))
    Pkg.instantiate()

    include("'"$docsBuild"'")
end
'
