#!/bin/bash
projectName=$(basename $(pwd))

julia --threads=auto -e "using Test, Documenter, $projectName; DocMeta.setdocmeta!($projectName, :DocTestSetup, :(using $projectName)); doctest($projectName, fix=true)"
