#!/bin/bash
project="$(basename "$PWD")"
cd benchmark || exit
julia --threads=auto --project -e '
using BenchmarkTools, Profile, FileIO
include("benchmarks.jl")

a = @bprofile '"$1"'
Profile.print(
    IOContext(open("/tmp/julprof.data", "w"), :displaysize=>(100000,1000)),
    format=:flat
)
profileData = Profile.retrieve()
save("/tmp/last_jul.jlprof", profileData[1], profileData[2])
display(a)
'
