#!/bin/bash
project="$(basename "$PWD")"
cd benchmark || exit
julia --threads=auto --project -e '
using BenchmarkTools;
include("PackageBenchmarks.jl")
results = run('"$1"', verbose=true)
print(results)
'
